<?php
session_start();

if (!isset($_SESSION['user_id'])) {
    header("Location: ../login.html");
    exit;
}

$fullname = $_SESSION['fullname'];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>Fees - Daar Al-Qur'aan</title>

    <link href="../bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../css/dashboard.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet" />
    <style>
        .month-btn { min-width: 56px; }
        .selected-month-btn {
            background-color: #0d6efd !important;
            color: #fff !important;
            border-color: #0d6efd !important;
        }
        .top-controls .form-control { min-width: 260px; }
    </style>
</head>
<body class="bg-light">

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid px-4">
            <a class="navbar-brand fw-bold arabic-text" href="dashboard.php">دار القرآن</a>
            <div class="d-flex align-items-center ms-auto">
                <span class="text-white me-3 fw-semibold">Welcome, <?php echo htmlspecialchars($fullname); ?></span>
                <a href="../php/logout.php" class="btn btn-outline-light btn-sm">Logout</a>
            </div>
        </div>
    </nav>

    <!-- Back Button -->
    <div class="container mt-3">
        <a href="dashboard.php" class="btn btn-outline-primary btn-sm">
            <i class="bi bi-arrow-left"></i> Back to Dashboard
        </a>
    </div>

    <!-- Page Content -->
    <div class="container-fluid mt-4">
        <div class="card p-3 shadow-sm">
            <div class="d-flex flex-wrap justify-content-between align-items-center mb-3 top-controls">
                <h3 class="fw-semibold text-primary mb-2 mb-md-0">Fees</h3>

                <!-- Search (not necessary but keep layout) -->
                <div class="input-group" style="max-width: 300px;">
                    <span class="input-group-text bg-white"><i class="bi bi-search"></i></span>
                    <input id="feesSearchInput" type="text" class="form-control" placeholder="Search by name...">
                </div>

                <div class="d-flex gap-2 align-items-center">
                    <select id="feesClassSelect" class="form-select form-select-sm me-2 w-auto">
                        <option value="Thursday Adults" selected>Thursday Adults</option>
                        <option value="Friday Kids">Friday Kids</option>
                        <option value="Friday Adults">Friday Adults</option>
                    </select>

                    <button id="feesRefreshBtn" class="btn btn-outline-secondary btn-sm">
                        <i class="bi bi-arrow-clockwise"></i> Refresh
                    </button>

                    <!-- Filter button -->
                    <button id="feesFilterBtn" class="btn btn-outline-info btn-sm" data-bs-toggle="modal" data-bs-target="#feesFilterModal">
                        <i class="bi bi-funnel"></i> Filter
                    </button>

                    <button id="feesSaveBtn" class="btn btn-primary btn-sm" disabled>
                        <i class="bi bi-save"></i> Save
                    </button>
                </div>
            </div>

            <!-- Month calendar controls (Jan..Dec) -->
            <div class="row mb-3 align-items-center">
                <div class="col-12 col-md-8 d-flex flex-wrap gap-2" id="feesMonthContainer" aria-hidden="false">
                    <!-- Buttons generated by JS -->
                </div>
                <div class="col-12 col-md-4 d-flex justify-content-end align-items-center">
                    <div>
                        <small class="text-muted">Selected month:</small>
                        <div id="selectedMonthText" class="fw-bold text-primary"></div>
                    </div>
                </div>
            </div>

            <!-- Fees Table -->
            <div class="table-responsive mt-2">
                <table class="table table-hover align-middle text-center">
                    <thead class="table-light">
                        <tr>
                            <th>#</th>
                            <th>Student Name</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="feesTableBody">
                        <!-- populated by JS -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    
    
    
    <!-- Filter Modal -->
    <div class="modal fade" id="feesFilterModal" tabindex="-1" aria-labelledby="feesFilterModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="feesFilterModalLabel">Filter by Status</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <select id="feesStatusFilter" class="form-select">
                        <option value="" selected>All</option>
                        <option value="Paid">Paid</option>
                        <option value="Unpaid">Unpaid</option>
                        <option value="Pending">Pending</option>
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" id="applyFeesFilter" class="btn btn-primary" data-bs-dismiss="modal">Apply</button>
                </div>
            </div>
        </div>
    </div>
    
    

    <!-- Bootstrap + JS -->
    <script src="../bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- optional: if you already have a shared fetchStudents.js you can keep it; fees.js will attempt to use it -->
    <script src="../js/fetchStudents.js"></script>
    <script src="../js/fees.js"></script>
</body>
</html>
